name: CondaEnvSolarPhysicsCourse
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.2
  - jupyter=1.0.0
  - pandas=1.1.0
  - python=3.8.5
  - numpy=1.19.1
  - matplotlib=3.3.0
  - astropy=4.0.1.post1
  - sunpy
