name: solarphysics
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aioftp=0.16.1
  - aiohttp=3.6.2
  - appdirs=1.4.3
  - argon2-cffi=20.1.0
  - astropy=4.0.1.post1
  - async-timeout=3.0.1
  - attrs=19.3.0
  - autopep8=1.5.4
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - beautifulsoup4=4.9.1
  - black=20.8b1
  - bleach=3.1.5
  - blosc=1.20.0
  - boost-cpp=1.72.0
  - brotli=1.0.7
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.12.5
  - cached-property=1.5.1
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.1
  - cfitsio=3.470
  - chardet=3.0.4
  - charls=2.1.0
  - click=7.1.2
  - cloudpickle=1.5.0
  - contextlib2=0.6.0.post1
  - cryptography=3.0
  - curl=7.71.1
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.22.0
  - dataclasses=0.7
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - drms=0.5.7
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.2
  - freexl=1.0.5
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.65.0
  - glymur=0.9.1
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heliopy=0.15.2
  - icu=64.2
  - idna=2.10
  - imagecodecs=2020.5.30
  - imageio=2.9.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - ipykernel=5.3.4
  - ipython=7.17.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isodate=0.6.0
  - jedi=0.17.2
  - jinja2=2.11.2
  - jpeg=9d
  - json-c=0.13.1
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.6
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - jxrlib=1.1
  - kealib=1.4.13
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lcms2=2.11
  - ld_impl_linux-64=2.34
  - lerc=2.2
  - libaec=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.71.1
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libnetcdf=4.7.4
  - libnghttp2=1.41.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libpq=12.3
  - libsodium=1.0.18
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - libzopfli=1.0.3
  - lxml=4.5.2
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.0
  - matplotlib-base=3.3.0
  - mistune=0.8.4
  - multidict=4.7.5
  - mypy_extensions=0.4.3
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - networkx=2.4
  - notebook=6.1.0
  - nspr=4.27
  - nss=3.47
  - numpy=1.19.1
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1i
  - packaging=20.4
  - pandas=1.1.0
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - parfive=1.1.0
  - parso=0.7.1
  - pathspec=0.8.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2
  - pixman=0.38.0
  - plotly=4.14.1
  - poppler=0.89.0
  - poppler-data=0.4.9
  - postgresql=12.3
  - proj=7.1.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qt=5.12.5
  - qtconsole=4.7.5
  - qtpy=1.9.0
  - readline=8.0
  - regex=2020.11.13
  - requests=2.24.0
  - requests-toolbelt=0.9.1
  - retrying=1.3.3
  - scikit-image=0.17.2
  - scipy=1.5.2
  - send2trash=1.5.0
  - setuptools=49.2.1
  - six=1.15.0
  - snappy=1.1.8
  - soupsieve=2.0.1
  - sqlalchemy=1.3.18
  - sqlite=3.32.3
  - sunpy=2.0.6
  - tbb=2020.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tifffile=2020.7.24
  - tiledb=2.0.8
  - tk=8.6.10
  - toml=0.10.1
  - toolz=0.10.0
  - tornado=6.0.4
  - tqdm=4.48.1
  - traitlets=4.3.3
  - typed-ast=1.4.2
  - typing_extensions=3.7.4.3
  - tzcode=2020a
  - urllib3=1.25.10
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.10
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - yarl=1.4.2
  - zeep=3.4.0
  - zeromq=4.3.2
  - zfp=0.5.5
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
      - alabaster==0.7.12
      - babel==2.9.0
      - cdflib==0.3.19
      - dill==0.3.3
      - docutils==0.16
      - imagesize==1.2.0
      - llvmlite==0.35.0
      - multiprocess==0.70.11.1
      - numba==0.52.0
      - numpydoc==1.1.0
      - pathos==0.2.7
      - pfsspy==0.6.3
      - pox==0.2.9
      - ppft==1.6.6.3
      - pyqt5-sip==4.19.18
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1
      - snowballstemmer==2.0.0
      - sphinx==3.4.2
      - sphinxcontrib-applehelp==1.0.2
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==1.0.3
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.4
      - spiceypy==4.0.0
      - streamtracer==1.0.0
